---
- name: Checking OS
  fail:
    msg: "Unsupported OS {{ ansible_distribution }}"
  when: ansible_distribution != "Ubuntu"

- name: Getting jenkins repo key
  apt_key:
    url: https://pkg.jenkins.io/debian-stable/jenkins-ci.org.key
    state: present

- name: Adding jenkins repository
  apt_repository:
    repo: deb http://pkg.jenkins.io/debian-stable binary/
    state: present
    update_cache: yes

- name: Installing jenkins
  apt:
    name: jenkins
    update_cache: yes
    state: present

- name: Start jenkins service
  service:
    name: jenkins
    state: restarted
    enabled: yes
