---
- name: Checking OS
  fail:
    msg: "Unsupported OS {{ ansible_distribution }}"
  when: ansible_distribution != "Ubuntu"

- name: Getting jenkins repo key
  apt_key:
    url: https://pkg.jenkins.io/debian-stable/jenkins-ci.org.key
    state: present

- name: Adding jenkins repository
  apt_repository:
    repo: deb http://pkg.jenkins.io/debian-stable binary/
    state: present
    update_cache: yes

- name: Installing jenkins
  apt:
    name: jenkins
    update_cache: yes
    state: present

- name: Start jenkins service
  service:
    name: jenkins
    state: restarted
    enabled: yes

- name: Installing jenkins plugins requirements (apt)
  apt:
    name: "{{ item }}"
    update_cache: yes
    state: present
  with_items: "{{ jenkins_plugins_apt_requirements }}"

- name: Installing jenkins plugins requirements (npm)
  npm:
    name: "{{ item }}"
    global: yes
    state: present
  with_items: "{{ jenkins_plugins_npm_requirements }}"

- include_vars: users.yml

- name: Adding jenkins plugins
  jenkins_plugin:
    name: "{{ item }}"
    params: "{{ jenkins_params }}"
    url_password: "{{ jenkins_password }}"
    state: present
    owner: root
  with_items: "{{ jenkins_plugins }}"
