---
- name: Unarchive nexus
  unarchive:
    src: https://sonatype-download.global.ssl.fastly.net/repository/repositoryManager/3/{{ nexus_version }}-unix.tar.gz
    dest: /var/
    creates: "/var/{{ nexus_version }}"
    remote_src: yes

- name: Copy nexus.service
  template:
    src: nexus.service.j2
    dest: /etc/systemd/system/nexus.service

- name: Starting nexus service
  service:
    name: nexus
    state: started
    enabled: yes


